# About Dataset

Parkinson's Data Set
This dataset is composed of a range of biomedical voice measurements from 31 people, 23 with Parkinson's disease (PD). Each column in the table is a particular voice measure, and each row corresponds to one of 195 voice recordings from these individuals ("name" column). The main aim of the data is to discriminate healthy people from those with PD, according to the "status" column which is set to 0 for healthy and 1 for PD.

The data is in ASCII CSV format. The rows of the CSV file contain an instance corresponding to one voice recording. There are around six recordings per patient, the name of the patient is identified in the first column.For further information or to pass on comments, please contact Max Little (little '@' robots.ox.ac.uk).

Further details are contained in the following reference -- if you use this dataset, please cite:
Max A. Little, Patrick E. McSharry, Eric J. Hunter, Lorraine O. Ramig (2008), 'Suitability of dysphonia measurements for telemonitoring of Parkinson's disease', IEEE Transactions on Biomedical Engineering (to appear).

# Attribute Information:

Matrix column entries (attributes):

1.name - ASCII subject name and recording number

2.MDVP:Fo(Hz) - Average vocal fundamental frequency

3.MDVP:Fhi(Hz) - Maximum vocal fundamental frequency
    
4.MDVP:Flo(Hz) - Minimum vocal fundamental frequency
    
5.MDVP:Jitter(%), MDVP:Jitter(Abs), MDVP:RAP, MDVP:PPQ, Jitter:DDP - Several measures of variation in fundamental frequency
                    
6.MDVP:Shimmer,MDVP:Shimmer(dB),Shimmer:APQ3,Shimmer:APQ5,MDVP:APQ,Shimmer:DDA - Several measures of variation in amplitude NHR, HNR - Two measures of the ratio of noise to tonal components in the voice

7.status - The health status of the subject (one) - Parkinson's, (zero) - healthy RPDE, D2 - Two nonlinear dynamical complexity measures

8.DFA - Signal fractal scaling exponent

9.spread1,spread2,PPE - Three nonlinear measures of fundamental frequency variation

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('parkinsons.data')

In [3]:
df.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [5]:
df=df.drop('name',axis=1)

In [6]:
df.head()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  MDVP:Jitter(Abs)  \
0      119.992       157.302        74.997         0.00784           0.00007   
1      122.400       148.650       113.819         0.00968           0.00008   
2      116.682       131.111       111.555         0.01050           0.00009   
3      116.676       137.871       111.366         0.00997           0.00009   
4      116.014       141.781       110.655         0.01284           0.00011   

   MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  MDVP:Shimmer(dB)  ...  \
0   0.00370   0.00554     0.01109       0.04374             0.426  ...   
1   0.00465   0.00696     0.01394       0.06134             0.626  ...   
2   0.00544   0.00781     0.01633       0.05233             0.482  ...   
3   0.00502   0.00698     0.01505       0.05492             0.517  ...   
4   0.00655   0.00908     0.01966       0.06425             0.584  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 23 columns]

In [7]:
df.columns

Index(['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE'],
      dtype='object')

In [8]:
df=df.rename(columns={'MDVP:Fo(Hz)':'MDVP_Fo_Hz',      'MDVP:Fhi(Hz)':'MDVP_Fhi_Hz',    'MDVP:Flo(Hz)':'MDVP_Flo_Hz',
                      'MDVP:Jitter(%)':'MDVP_Jitter_%','MDVP:Jitter(Abs)':'MDVP_Jitter_Abs', 'MDVP:RAP':'MDVP_RAP', 
                      'MDVP:PPQ':'MDVP_PPQ', 'Jitter:DDP':'Jitter_DDP','MDVP:Shimmer':'MDVP_Shimmer', 
                      'MDVP:Shimmer(dB)':'MDVP_Shimmer_dB', 'Shimmer:APQ3':'Shimmer_APQ_3', 'Shimmer:APQ5':'Shimmer_APQ_5',
       'MDVP:APQ':'MDVP_APQ', 'Shimmer:DDA':'Shimmer_DDA',})

In [9]:
df.columns

Index(['MDVP_Fo_Hz', 'MDVP_Fhi_Hz', 'MDVP_Flo_Hz', 'MDVP_Jitter_%',
       'MDVP_Jitter_Abs', 'MDVP_RAP', 'MDVP_PPQ', 'Jitter_DDP', 'MDVP_Shimmer',
       'MDVP_Shimmer_dB', 'Shimmer_APQ_3', 'Shimmer_APQ_5', 'MDVP_APQ',
       'Shimmer_DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA', 'spread1',
       'spread2', 'D2', 'PPE'],
      dtype='object')

In [10]:
from sklearn.model_selection import train_test_split
x=df.drop('status',axis=1)
y=df.status
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=345)

In [11]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
x_train=sc.fit_transform(x_train)

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for Logistic Regression',accuracy_score(y_test,y_pred))

[[15  0]
 [24  0]]
Accuracy for Logistic Regression 0.38461538461538464


In [13]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
svc=SVC(class_weight='balanced')
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for SVC (RBF)',accuracy_score(y_test,y_pred))

[[ 0 15]
 [ 0 24]]
Accuracy for SVC (RBF) 0.6153846153846154


In [14]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
svc=SVC(class_weight='balanced',kernel='linear')
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for SVC(Linear)',accuracy_score(y_test,y_pred))


[[ 2 13]
 [ 2 22]]
Accuracy for SVC(Linear) 0.6153846153846154


In [15]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
svc=SVC(class_weight='balanced',kernel='poly')
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for SVC (Poly)',accuracy_score(y_test,y_pred))

[[15  0]
 [24  0]]
Accuracy for SVC (Poly) 0.38461538461538464


In [16]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
svc=SVC(class_weight='balanced',kernel='sigmoid')
svc.fit(x_train,y_train)
y_pred=svc.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for SVC(Sigmoid)',accuracy_score(y_test,y_pred))


[[15  0]
 [24  0]]
Accuracy for SVC(Sigmoid) 0.38461538461538464


In [17]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(class_weight='balanced')
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for Decision Tree (GINI)',accuracy_score(y_test,y_pred))

[[15  0]
 [12 12]]
Accuracy for Decision Tree (GINI) 0.6923076923076923


In [18]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(class_weight='balanced',criterion='entropy',max_depth=5)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for Decision Tree (ENTROPY)',accuracy_score(y_test,y_pred))

[[15  0]
 [12 12]]
Accuracy for Decision Tree (ENTROPY) 0.6923076923076923


In [19]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(class_weight='balanced')
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for Random Forest',accuracy_score(y_test,y_pred))

[[10  5]
 [ 8 16]]
Accuracy for Random Forest 0.6666666666666666


In [20]:
from sklearn.ensemble import ExtraTreesClassifier
exc=ExtraTreesClassifier(class_weight='balanced')
exc.fit(x_train,y_train)
y_pred=exc.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for Extratrees Classifier',accuracy_score(y_test,y_pred))

[[15  0]
 [24  0]]
Accuracy for Extratrees Classifier 0.38461538461538464


In [21]:
from catboost import CatBoostClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
cbc=CatBoostClassifier()
cbc.fit(x_train,y_train)
y_pred=cbc.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for CatBoost Classifier',accuracy_score(y_test,y_pred))

Learning rate set to 0.00466
0:	learn: 0.6881011	total: 388ms	remaining: 6m 27s
1:	learn: 0.6847345	total: 482ms	remaining: 4m
2:	learn: 0.6805422	total: 512ms	remaining: 2m 50s
3:	learn: 0.6767162	total: 579ms	remaining: 2m 24s
4:	learn: 0.6731048	total: 610ms	remaining: 2m 1s
5:	learn: 0.6688288	total: 731ms	remaining: 2m 1s
6:	learn: 0.6638891	total: 761ms	remaining: 1m 47s
7:	learn: 0.6602894	total: 868ms	remaining: 1m 47s
8:	learn: 0.6559933	total: 929ms	remaining: 1m 42s
9:	learn: 0.6511996	total: 945ms	remaining: 1m 33s
10:	learn: 0.6466554	total: 1.01s	remaining: 1m 30s
11:	learn: 0.6421386	total: 1.04s	remaining: 1m 25s
12:	learn: 0.6367405	total: 1.15s	remaining: 1m 27s
13:	learn: 0.6328004	total: 1.22s	remaining: 1m 25s
14:	learn: 0.6289093	total: 1.25s	remaining: 1m 21s
15:	learn: 0.6249447	total: 1.32s	remaining: 1m 20s
16:	learn: 0.6199186	total: 1.38s	remaining: 1m 20s
17:	learn: 0.6168762	total: 1.45s	remaining: 1m 19s
18:	learn: 0.6125609	total: 1.47s	remaining: 1m 16s

162:	learn: 0.2795091	total: 8.84s	remaining: 45.4s
163:	learn: 0.2780739	total: 8.88s	remaining: 45.3s
164:	learn: 0.2769662	total: 8.95s	remaining: 45.3s
165:	learn: 0.2758276	total: 9s	remaining: 45.2s
166:	learn: 0.2748152	total: 9.02s	remaining: 45s
167:	learn: 0.2741754	total: 9.06s	remaining: 44.9s
168:	learn: 0.2731011	total: 9.1s	remaining: 44.8s
169:	learn: 0.2713670	total: 9.13s	remaining: 44.6s
170:	learn: 0.2696120	total: 9.16s	remaining: 44.4s
171:	learn: 0.2682527	total: 9.21s	remaining: 44.3s
172:	learn: 0.2671445	total: 9.25s	remaining: 44.2s
173:	learn: 0.2660243	total: 9.28s	remaining: 44.1s
174:	learn: 0.2651149	total: 9.34s	remaining: 44s
175:	learn: 0.2642224	total: 9.39s	remaining: 44s
176:	learn: 0.2631298	total: 9.46s	remaining: 44s
177:	learn: 0.2624909	total: 9.49s	remaining: 43.8s
178:	learn: 0.2615378	total: 9.55s	remaining: 43.8s
179:	learn: 0.2601124	total: 9.61s	remaining: 43.8s
180:	learn: 0.2593356	total: 9.69s	remaining: 43.8s
181:	learn: 0.2582470	to

324:	learn: 0.1529615	total: 17.1s	remaining: 35.6s
325:	learn: 0.1524778	total: 17.2s	remaining: 35.5s
326:	learn: 0.1519645	total: 17.2s	remaining: 35.5s
327:	learn: 0.1515662	total: 17.3s	remaining: 35.4s
328:	learn: 0.1510645	total: 17.4s	remaining: 35.4s
329:	learn: 0.1504377	total: 17.4s	remaining: 35.4s
330:	learn: 0.1499134	total: 17.5s	remaining: 35.3s
331:	learn: 0.1493012	total: 17.5s	remaining: 35.3s
332:	learn: 0.1487583	total: 17.6s	remaining: 35.2s
333:	learn: 0.1483519	total: 17.6s	remaining: 35.1s
334:	learn: 0.1479413	total: 17.6s	remaining: 35s
335:	learn: 0.1476392	total: 17.7s	remaining: 34.9s
336:	learn: 0.1472536	total: 17.7s	remaining: 34.8s
337:	learn: 0.1468301	total: 17.8s	remaining: 34.8s
338:	learn: 0.1463541	total: 17.8s	remaining: 34.7s
339:	learn: 0.1460390	total: 17.9s	remaining: 34.7s
340:	learn: 0.1457012	total: 17.9s	remaining: 34.6s
341:	learn: 0.1452983	total: 18s	remaining: 34.5s
342:	learn: 0.1448195	total: 18s	remaining: 34.5s
343:	learn: 0.1445

487:	learn: 0.0970454	total: 24.7s	remaining: 25.9s
488:	learn: 0.0967748	total: 24.7s	remaining: 25.8s
489:	learn: 0.0965955	total: 24.8s	remaining: 25.8s
490:	learn: 0.0962892	total: 24.8s	remaining: 25.7s
491:	learn: 0.0960040	total: 24.9s	remaining: 25.7s
492:	learn: 0.0958438	total: 24.9s	remaining: 25.6s
493:	learn: 0.0956169	total: 24.9s	remaining: 25.5s
494:	learn: 0.0954183	total: 25s	remaining: 25.5s
495:	learn: 0.0952814	total: 25s	remaining: 25.4s
496:	learn: 0.0950409	total: 25.1s	remaining: 25.4s
497:	learn: 0.0948463	total: 25.2s	remaining: 25.4s
498:	learn: 0.0945822	total: 25.2s	remaining: 25.3s
499:	learn: 0.0944223	total: 25.3s	remaining: 25.3s
500:	learn: 0.0941223	total: 25.3s	remaining: 25.2s
501:	learn: 0.0938536	total: 25.3s	remaining: 25.1s
502:	learn: 0.0936497	total: 25.4s	remaining: 25.1s
503:	learn: 0.0935097	total: 25.4s	remaining: 25s
504:	learn: 0.0933365	total: 25.4s	remaining: 24.9s
505:	learn: 0.0931528	total: 25.4s	remaining: 24.8s
506:	learn: 0.0928

650:	learn: 0.0670832	total: 31.3s	remaining: 16.8s
651:	learn: 0.0669724	total: 31.3s	remaining: 16.7s
652:	learn: 0.0668472	total: 31.3s	remaining: 16.7s
653:	learn: 0.0666953	total: 31.4s	remaining: 16.6s
654:	learn: 0.0665686	total: 31.4s	remaining: 16.5s
655:	learn: 0.0664617	total: 31.4s	remaining: 16.5s
656:	learn: 0.0662964	total: 31.5s	remaining: 16.4s
657:	learn: 0.0661318	total: 31.5s	remaining: 16.4s
658:	learn: 0.0659367	total: 31.5s	remaining: 16.3s
659:	learn: 0.0657915	total: 31.6s	remaining: 16.3s
660:	learn: 0.0656333	total: 31.6s	remaining: 16.2s
661:	learn: 0.0654353	total: 31.7s	remaining: 16.2s
662:	learn: 0.0652316	total: 31.7s	remaining: 16.1s
663:	learn: 0.0650520	total: 31.7s	remaining: 16.1s
664:	learn: 0.0649381	total: 31.8s	remaining: 16s
665:	learn: 0.0648100	total: 31.8s	remaining: 15.9s
666:	learn: 0.0646674	total: 31.8s	remaining: 15.9s
667:	learn: 0.0644352	total: 31.9s	remaining: 15.8s
668:	learn: 0.0642657	total: 31.9s	remaining: 15.8s
669:	learn: 0.

810:	learn: 0.0489956	total: 36.4s	remaining: 8.48s
811:	learn: 0.0489214	total: 36.4s	remaining: 8.43s
812:	learn: 0.0488177	total: 36.4s	remaining: 8.38s
813:	learn: 0.0487501	total: 36.4s	remaining: 8.33s
814:	learn: 0.0486989	total: 36.5s	remaining: 8.28s
815:	learn: 0.0485745	total: 36.5s	remaining: 8.23s
816:	learn: 0.0485150	total: 36.6s	remaining: 8.19s
817:	learn: 0.0484220	total: 36.6s	remaining: 8.14s
818:	learn: 0.0483174	total: 36.6s	remaining: 8.09s
819:	learn: 0.0482466	total: 36.6s	remaining: 8.04s
820:	learn: 0.0481819	total: 36.7s	remaining: 7.99s
821:	learn: 0.0480431	total: 36.7s	remaining: 7.94s
822:	learn: 0.0479743	total: 36.7s	remaining: 7.9s
823:	learn: 0.0478787	total: 36.7s	remaining: 7.85s
824:	learn: 0.0478567	total: 36.7s	remaining: 7.79s
825:	learn: 0.0477559	total: 36.8s	remaining: 7.75s
826:	learn: 0.0476687	total: 36.8s	remaining: 7.7s
827:	learn: 0.0475738	total: 36.8s	remaining: 7.65s
828:	learn: 0.0475225	total: 36.9s	remaining: 7.6s
829:	learn: 0.0

976:	learn: 0.0368709	total: 40.4s	remaining: 950ms
977:	learn: 0.0368170	total: 40.4s	remaining: 908ms
978:	learn: 0.0367321	total: 40.4s	remaining: 866ms
979:	learn: 0.0366486	total: 40.4s	remaining: 825ms
980:	learn: 0.0366259	total: 40.4s	remaining: 783ms
981:	learn: 0.0365734	total: 40.5s	remaining: 742ms
982:	learn: 0.0364870	total: 40.5s	remaining: 701ms
983:	learn: 0.0364304	total: 40.5s	remaining: 659ms
984:	learn: 0.0363748	total: 40.5s	remaining: 618ms
985:	learn: 0.0362887	total: 40.6s	remaining: 576ms
986:	learn: 0.0362417	total: 40.6s	remaining: 535ms
987:	learn: 0.0361929	total: 40.6s	remaining: 493ms
988:	learn: 0.0361323	total: 40.6s	remaining: 452ms
989:	learn: 0.0361083	total: 40.7s	remaining: 411ms
990:	learn: 0.0360406	total: 40.7s	remaining: 369ms
991:	learn: 0.0360106	total: 40.7s	remaining: 328ms
992:	learn: 0.0359474	total: 40.7s	remaining: 287ms
993:	learn: 0.0358728	total: 40.7s	remaining: 246ms
994:	learn: 0.0357812	total: 40.8s	remaining: 205ms
995:	learn: 

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=345)
from imblearn.over_sampling import SMOTE
sm=SMOTE()
x_train,y_train=sm.fit_resample(x_train,y_train)

In [23]:
from catboost import CatBoostClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
cbc=CatBoostClassifier()
cbc.fit(x_train,y_train)
y_pred=cbc.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for CatBoost Classifier',accuracy_score(y_test,y_pred))

Learning rate set to 0.005661
0:	learn: 0.6885542	total: 48ms	remaining: 47.9s
1:	learn: 0.6829011	total: 69.3ms	remaining: 34.6s
2:	learn: 0.6785236	total: 109ms	remaining: 36.1s
3:	learn: 0.6710069	total: 158ms	remaining: 39.3s
4:	learn: 0.6656252	total: 181ms	remaining: 35.9s
5:	learn: 0.6603851	total: 215ms	remaining: 35.7s
6:	learn: 0.6557134	total: 255ms	remaining: 36.2s
7:	learn: 0.6510461	total: 277ms	remaining: 34.3s
8:	learn: 0.6463932	total: 305ms	remaining: 33.5s
9:	learn: 0.6421108	total: 329ms	remaining: 32.5s
10:	learn: 0.6368208	total: 356ms	remaining: 32s
11:	learn: 0.6300674	total: 377ms	remaining: 31s
12:	learn: 0.6257468	total: 400ms	remaining: 30.3s
13:	learn: 0.6209632	total: 421ms	remaining: 29.7s
14:	learn: 0.6171917	total: 469ms	remaining: 30.8s
15:	learn: 0.6121301	total: 490ms	remaining: 30.1s
16:	learn: 0.6074917	total: 526ms	remaining: 30.4s
17:	learn: 0.6033511	total: 562ms	remaining: 30.6s
18:	learn: 0.5980219	total: 581ms	remaining: 30s
19:	learn: 0.5931

163:	learn: 0.2302607	total: 7.12s	remaining: 36.3s
164:	learn: 0.2292385	total: 7.19s	remaining: 36.4s
165:	learn: 0.2280290	total: 7.22s	remaining: 36.3s
166:	learn: 0.2264359	total: 7.25s	remaining: 36.2s
167:	learn: 0.2256719	total: 7.29s	remaining: 36.1s
168:	learn: 0.2244541	total: 7.32s	remaining: 36s
169:	learn: 0.2237167	total: 7.37s	remaining: 36s
170:	learn: 0.2225065	total: 7.42s	remaining: 36s
171:	learn: 0.2207437	total: 7.45s	remaining: 35.8s
172:	learn: 0.2197192	total: 7.51s	remaining: 35.9s
173:	learn: 0.2187919	total: 7.57s	remaining: 36s
174:	learn: 0.2182140	total: 7.63s	remaining: 36s
175:	learn: 0.2168405	total: 7.65s	remaining: 35.8s
176:	learn: 0.2158719	total: 7.7s	remaining: 35.8s
177:	learn: 0.2150012	total: 7.72s	remaining: 35.7s
178:	learn: 0.2138827	total: 7.75s	remaining: 35.5s
179:	learn: 0.2128878	total: 7.8s	remaining: 35.5s
180:	learn: 0.2116785	total: 7.82s	remaining: 35.4s
181:	learn: 0.2107678	total: 7.85s	remaining: 35.3s
182:	learn: 0.2098039	to

322:	learn: 0.1151688	total: 14.4s	remaining: 30.2s
323:	learn: 0.1148749	total: 14.5s	remaining: 30.2s
324:	learn: 0.1144477	total: 14.5s	remaining: 30.2s
325:	learn: 0.1142273	total: 14.6s	remaining: 30.3s
326:	learn: 0.1138694	total: 14.7s	remaining: 30.3s
327:	learn: 0.1133338	total: 14.7s	remaining: 30.2s
328:	learn: 0.1128344	total: 14.8s	remaining: 30.2s
329:	learn: 0.1123064	total: 14.9s	remaining: 30.3s
330:	learn: 0.1120112	total: 14.9s	remaining: 30.2s
331:	learn: 0.1115943	total: 15s	remaining: 30.2s
332:	learn: 0.1112661	total: 15.1s	remaining: 30.2s
333:	learn: 0.1110446	total: 15.1s	remaining: 30.2s
334:	learn: 0.1106005	total: 15.2s	remaining: 30.1s
335:	learn: 0.1102126	total: 15.2s	remaining: 30.1s
336:	learn: 0.1097781	total: 15.3s	remaining: 30.1s
337:	learn: 0.1093073	total: 15.4s	remaining: 30.1s
338:	learn: 0.1090223	total: 15.5s	remaining: 30.1s
339:	learn: 0.1088091	total: 15.5s	remaining: 30.1s
340:	learn: 0.1085152	total: 15.6s	remaining: 30.1s
341:	learn: 0.

481:	learn: 0.0716396	total: 25.5s	remaining: 27.4s
482:	learn: 0.0715118	total: 25.6s	remaining: 27.4s
483:	learn: 0.0714256	total: 25.7s	remaining: 27.4s
484:	learn: 0.0712897	total: 25.7s	remaining: 27.3s
485:	learn: 0.0710393	total: 25.8s	remaining: 27.3s
486:	learn: 0.0708205	total: 25.9s	remaining: 27.3s
487:	learn: 0.0705638	total: 25.9s	remaining: 27.2s
488:	learn: 0.0703853	total: 26s	remaining: 27.2s
489:	learn: 0.0702346	total: 26.1s	remaining: 27.1s
490:	learn: 0.0700641	total: 26.2s	remaining: 27.2s
491:	learn: 0.0698937	total: 26.3s	remaining: 27.1s
492:	learn: 0.0697003	total: 26.3s	remaining: 27.1s
493:	learn: 0.0696064	total: 26.4s	remaining: 27.1s
494:	learn: 0.0693434	total: 26.5s	remaining: 27s
495:	learn: 0.0691342	total: 26.5s	remaining: 26.9s
496:	learn: 0.0689204	total: 26.6s	remaining: 26.9s
497:	learn: 0.0687222	total: 26.7s	remaining: 26.9s
498:	learn: 0.0686011	total: 26.7s	remaining: 26.8s
499:	learn: 0.0683979	total: 26.8s	remaining: 26.8s
500:	learn: 0.06

641:	learn: 0.0486554	total: 35.9s	remaining: 20s
642:	learn: 0.0485610	total: 36s	remaining: 20s
643:	learn: 0.0484542	total: 36.1s	remaining: 19.9s
644:	learn: 0.0483534	total: 36.2s	remaining: 19.9s
645:	learn: 0.0482435	total: 36.2s	remaining: 19.8s
646:	learn: 0.0481742	total: 36.3s	remaining: 19.8s
647:	learn: 0.0480131	total: 36.4s	remaining: 19.7s
648:	learn: 0.0479010	total: 36.4s	remaining: 19.7s
649:	learn: 0.0477780	total: 36.5s	remaining: 19.6s
650:	learn: 0.0477164	total: 36.5s	remaining: 19.6s
651:	learn: 0.0476160	total: 36.6s	remaining: 19.5s
652:	learn: 0.0475154	total: 36.6s	remaining: 19.5s
653:	learn: 0.0474005	total: 36.7s	remaining: 19.4s
654:	learn: 0.0472923	total: 36.8s	remaining: 19.4s
655:	learn: 0.0472124	total: 36.9s	remaining: 19.3s
656:	learn: 0.0471462	total: 36.9s	remaining: 19.3s
657:	learn: 0.0470321	total: 37s	remaining: 19.2s
658:	learn: 0.0469131	total: 37s	remaining: 19.2s
659:	learn: 0.0468175	total: 37.1s	remaining: 19.1s
660:	learn: 0.0467331	

802:	learn: 0.0347596	total: 45.5s	remaining: 11.2s
803:	learn: 0.0346904	total: 45.5s	remaining: 11.1s
804:	learn: 0.0346298	total: 45.5s	remaining: 11s
805:	learn: 0.0345751	total: 45.5s	remaining: 11s
806:	learn: 0.0344901	total: 45.6s	remaining: 10.9s
807:	learn: 0.0344037	total: 45.6s	remaining: 10.8s
808:	learn: 0.0343288	total: 45.6s	remaining: 10.8s
809:	learn: 0.0342905	total: 45.7s	remaining: 10.7s
810:	learn: 0.0342283	total: 45.7s	remaining: 10.7s
811:	learn: 0.0341793	total: 45.7s	remaining: 10.6s
812:	learn: 0.0341209	total: 45.8s	remaining: 10.5s
813:	learn: 0.0340549	total: 45.8s	remaining: 10.5s
814:	learn: 0.0340073	total: 45.8s	remaining: 10.4s
815:	learn: 0.0339221	total: 45.8s	remaining: 10.3s
816:	learn: 0.0338818	total: 45.9s	remaining: 10.3s
817:	learn: 0.0338416	total: 45.9s	remaining: 10.2s
818:	learn: 0.0338068	total: 45.9s	remaining: 10.1s
819:	learn: 0.0337837	total: 45.9s	remaining: 10.1s
820:	learn: 0.0337024	total: 46s	remaining: 10s
821:	learn: 0.033631

961:	learn: 0.0258330	total: 48.9s	remaining: 1.93s
962:	learn: 0.0257826	total: 49s	remaining: 1.88s
963:	learn: 0.0257239	total: 49s	remaining: 1.83s
964:	learn: 0.0256827	total: 49s	remaining: 1.78s
965:	learn: 0.0256424	total: 49s	remaining: 1.72s
966:	learn: 0.0256211	total: 49s	remaining: 1.67s
967:	learn: 0.0255765	total: 49.1s	remaining: 1.62s
968:	learn: 0.0255528	total: 49.1s	remaining: 1.57s
969:	learn: 0.0255157	total: 49.2s	remaining: 1.52s
970:	learn: 0.0254955	total: 49.2s	remaining: 1.47s
971:	learn: 0.0254607	total: 49.3s	remaining: 1.42s
972:	learn: 0.0254224	total: 49.4s	remaining: 1.37s
973:	learn: 0.0253818	total: 49.4s	remaining: 1.32s
974:	learn: 0.0253376	total: 49.4s	remaining: 1.27s
975:	learn: 0.0252930	total: 49.5s	remaining: 1.22s
976:	learn: 0.0252524	total: 49.5s	remaining: 1.17s
977:	learn: 0.0252105	total: 49.6s	remaining: 1.11s
978:	learn: 0.0251795	total: 49.6s	remaining: 1.06s
979:	learn: 0.0251621	total: 49.6s	remaining: 1.01s
980:	learn: 0.0251109	

In [24]:
fea_imp=pd.DataFrame()
fea_imp['Features']=x_train.columns
fea_imp['Importance']=rf.feature_importances_


In [25]:
fea_imp=fea_imp.sort_values('Importance',ascending=False)

In [26]:
fea_imp

Features  Importance
18          spread1    0.120114
21              PPE    0.120048
12         MDVP_APQ    0.078687
19          spread2    0.075035
11    Shimmer_APQ_5    0.066645
0        MDVP_Fo_Hz    0.066020
1       MDVP_Fhi_Hz    0.050226
17              DFA    0.039109
13      Shimmer_DDA    0.035290
2       MDVP_Flo_Hz    0.034951
7        Jitter_DDP    0.033649
16             RPDE    0.031821
20               D2    0.031241
6          MDVP_PPQ    0.030515
10    Shimmer_APQ_3    0.029551
9   MDVP_Shimmer_dB    0.027917
14              NHR    0.023827
5          MDVP_RAP    0.023742
15              HNR    0.022121
3     MDVP_Jitter_%    0.021841
8      MDVP_Shimmer    0.021492
4   MDVP_Jitter_Abs    0.016160

In [27]:
fea_imp=fea_imp.head(9)

In [28]:
fea_imp

Features  Importance
18        spread1    0.120114
21            PPE    0.120048
12       MDVP_APQ    0.078687
19        spread2    0.075035
11  Shimmer_APQ_5    0.066645
0      MDVP_Fo_Hz    0.066020
1     MDVP_Fhi_Hz    0.050226
17            DFA    0.039109
13    Shimmer_DDA    0.035290

In [29]:
l1=list(fea_imp.Features)
l1

['spread1',
 'PPE',
 'MDVP_APQ',
 'spread2',
 'Shimmer_APQ_5',
 'MDVP_Fo_Hz',
 'MDVP_Fhi_Hz',
 'DFA',
 'Shimmer_DDA']

In [30]:
l1.append('status')

In [31]:
l1

['spread1',
 'PPE',
 'MDVP_APQ',
 'spread2',
 'Shimmer_APQ_5',
 'MDVP_Fo_Hz',
 'MDVP_Fhi_Hz',
 'DFA',
 'Shimmer_DDA',
 'status']

In [32]:
df=df.loc[:,['PPE',
 'MDVP_APQ',
 'spread2',
 'MDVP_Fhi_Hz',
 'MDVP_Fo_Hz',
 'Shimmer_APQ_5',
 'Jitter_DDP',
 'RPDE',
 'status']]

In [33]:
df.head()

PPE  MDVP_APQ   spread2  MDVP_Fhi_Hz  MDVP_Fo_Hz  Shimmer_APQ_5  \
0  0.284654   0.02971  0.266482      157.302     119.992        0.03130   
1  0.368674   0.04368  0.335590      148.650     122.400        0.04518   
2  0.332634   0.03590  0.311173      131.111     116.682        0.03858   
3  0.368975   0.03772  0.334147      137.871     116.676        0.04005   
4  0.410335   0.04465  0.234513      141.781     116.014        0.04825   

   Jitter_DDP      RPDE  status  
0     0.01109  0.414783       1  
1     0.01394  0.458359       1  
2     0.01633  0.429895       1  
3     0.01505  0.434969       1  
4     0.01966  0.417356       1

In [34]:
df[df.status==0]

PPE  MDVP_APQ   spread2  MDVP_Fhi_Hz  MDVP_Fo_Hz  Shimmer_APQ_5  \
30   0.085569   0.00802  0.177551      206.896     197.076        0.00680   
31   0.068501   0.00762  0.173319      209.512     199.228        0.00641   
32   0.096320   0.00951  0.175181      215.203     198.383        0.00825   
33   0.056141   0.00719  0.178540      211.604     202.266        0.00606   
34   0.044539   0.00726  0.163519      211.526     203.184        0.00610   
35   0.057610   0.00957  0.170183      210.565     201.464        0.00760   
42   0.095032   0.01133  0.098648      247.326     237.226        0.01024   
43   0.117399   0.01251  0.158266      248.834     241.404        0.01038   
44   0.091470   0.01033  0.091608      250.912     243.439        0.00898   
45   0.102706   0.01014  0.102083      255.034     242.852        0.00879   
46   0.097336   0.01149  0.127642      262.090     245.510        0.00977   
47   0.086398   0.00860  0.200873      261.487     252.455        0.00730   
48   0.133867   0.01433  0.266392      128.611     122.188        0.00776   
49   0.128872   0.01400  0.264967      130.049     122.964        0.00802   
50   0.103561   0.01685  0.254498      135.069     124.445        0.01024   
51   0.105993   0.01614  0.291954      134.231     126.344        0.00959   
52   0.119308   0.01677  0.220434      138.052     128.001        0.01072   
53   0.147491   0.01947  0.269866      139.867     129.336        0.01219   
60   0.101516   0.01382  0.066994      237.494     209.144        0.01258   
61   0.098555   0.01340  0.086372      238.987     223.365        0.01296   
62   0.103224   0.01200  0.095882      231.345     222.236        0.01108   
63   0.093534   0.01179  0.018689      234.619     228.832        0.01075   
64   0.073581   0.01016  0.056844      252.221     229.401        0.00957   
65   0.091546   0.01234  0.006274      239.541     228.969        0.01160   
165  0.119652   0.01621  0.172270      244.663     236.200        0.01426   
166  0.091604   0.00882  0.176316      243.709     237.323        0.00747   
167  0.075587   0.01367  0.160414      264.919     260.105        0.01230   
168  0.202879   0.01439  0.164529      217.627     197.569        0.01272   
169  0.100881   0.01344  0.073298      245.135     240.301        0.01191   
170  0.096220   0.01255  0.171088      272.210     244.990        0.01121   
171  0.160376   0.01140  0.218885      133.374     112.547        0.00786   
172  0.174152   0.01285  0.192375      113.597     110.739        0.00950   
173  0.179677   0.01148  0.192150      116.443     113.715        0.00905   
174  0.163118   0.01318  0.229298      144.466     117.004        0.01062   
175  0.184067   0.01133  0.197938      123.109     115.380        0.00933   
176  0.174429   0.01331  0.109256      129.038     116.388        0.01021   
183  0.215724   0.01949  0.191576      123.925     117.226        0.01223   
184  0.252404   0.01756  0.206768      217.552     116.848        0.01144   
185  0.214346   0.01691  0.133917      177.291     116.286        0.00990   
186  0.120605   0.01491  0.153310      592.030     116.556        0.00972   
187  0.138868   0.01144  0.116636      581.289     116.342        0.00789   
188  0.121777   0.01095  0.149694      119.167     114.563        0.00721   
189  0.112838   0.01758  0.159890      262.707     201.774        0.01582   
190  0.133050   0.02745  0.121952      230.978     174.188        0.02498   
191  0.168895   0.01879  0.129303      253.017     209.516        0.01657   
192  0.131728   0.01667  0.158453      240.005     174.688        0.01365   
193  0.123306   0.01588  0.207454      396.961     198.764        0.01321   
194  0.148569   0.01373  0.190667      260.277     214.289        0.01161   

     Jitter_DDP      RPDE  status  
30      0.00498  0.422229       0  
31      0.00402  0.432439       0  
32      0.00339  0.465946       0  
33      0.00278  0.368535       0  
34      0.00283  0.340068       0  
35      0.00314  0.3

In [35]:
df.columns

Index(['PPE', 'MDVP_APQ', 'spread2', 'MDVP_Fhi_Hz', 'MDVP_Fo_Hz',
       'Shimmer_APQ_5', 'Jitter_DDP', 'RPDE', 'status'],
      dtype='object')

In [36]:
df.columns

Index(['PPE', 'MDVP_APQ', 'spread2', 'MDVP_Fhi_Hz', 'MDVP_Fo_Hz',
       'Shimmer_APQ_5', 'Jitter_DDP', 'RPDE', 'status'],
      dtype='object')

In [37]:
df.shape

(195, 9)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   PPE            195 non-null    float64
 1   MDVP_APQ       195 non-null    float64
 2   spread2        195 non-null    float64
 3   MDVP_Fhi_Hz    195 non-null    float64
 4   MDVP_Fo_Hz     195 non-null    float64
 5   Shimmer_APQ_5  195 non-null    float64
 6   Jitter_DDP     195 non-null    float64
 7   RPDE           195 non-null    float64
 8   status         195 non-null    int64  
dtypes: float64(8), int64(1)
memory usage: 13.8 KB


In [39]:
df.describe()

PPE    MDVP_APQ     spread2  MDVP_Fhi_Hz  MDVP_Fo_Hz  \
count  195.000000  195.000000  195.000000   195.000000  195.000000   
mean     0.206552    0.024081    0.226510   197.104918  154.228641   
std      0.090119    0.016947    0.083406    91.491548   41.390065   
min      0.044539    0.007190    0.006274   102.145000   88.333000   
25%      0.137451    0.013080    0.174351   134.862500  117.572000   
50%      0.194052    0.018260    0.218885   175.829000  148.790000   
75%      0.252980    0.029400    0.279234   224.205500  182.769000   
max      0.527367    0.137780    0.450493   592.030000  260.105000   

       Shimmer_APQ_5  Jitter_DDP        RPDE      status  
count     195.000000  195.000000  195.000000  195.000000  
mean        0.017878    0.009920    0.498536    0.753846  
std         0.012024    0.008903    0.103942    0.431878  
min         0.005700    0.002040    0.256570    0.000000  
25%         0.009580    0.004985    0.421306    1.000000  
50%         0.013470    0.007490    0.495954    1.000000  
75%         0.022380    0.011505    0.587562    1.000000  
max         0.079400    0.064330    0.685151    1.000000

In [40]:
x=df.drop('status',axis=1)
y=df.status
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=345)

In [41]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((156, 8), (39, 8), (156,), (39,))

In [42]:
from catboost import CatBoostClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
cbc_f=CatBoostClassifier()
cbc_f.fit(x_train,y_train)
y_pred=cbc_f.predict(x_test)
tab1=confusion_matrix(y_test,y_pred)
print(tab1)
print('Accuracy for CatBoost Classifier',accuracy_score(y_test,y_pred))

Learning rate set to 0.00466
0:	learn: 0.6876839	total: 5.6ms	remaining: 5.59s
1:	learn: 0.6815775	total: 10.2ms	remaining: 5.11s
2:	learn: 0.6768241	total: 14.3ms	remaining: 4.76s
3:	learn: 0.6716573	total: 18.7ms	remaining: 4.66s
4:	learn: 0.6674321	total: 23.4ms	remaining: 4.65s
5:	learn: 0.6631072	total: 27.8ms	remaining: 4.6s
6:	learn: 0.6582131	total: 32.2ms	remaining: 4.56s
7:	learn: 0.6536570	total: 36.5ms	remaining: 4.52s
8:	learn: 0.6478448	total: 40.9ms	remaining: 4.5s
9:	learn: 0.6430525	total: 45.4ms	remaining: 4.49s
10:	learn: 0.6392828	total: 49.8ms	remaining: 4.48s
11:	learn: 0.6348478	total: 54.4ms	remaining: 4.47s
12:	learn: 0.6299499	total: 59.2ms	remaining: 4.49s
13:	learn: 0.6258898	total: 64.8ms	remaining: 4.56s
14:	learn: 0.6209675	total: 69.6ms	remaining: 4.57s
15:	learn: 0.6154484	total: 74ms	remaining: 4.55s
16:	learn: 0.6115008	total: 79.4ms	remaining: 4.59s
17:	learn: 0.6077928	total: 84.2ms	remaining: 4.59s
18:	learn: 0.6036503	total: 89.2ms	remaining: 4.61

196:	learn: 0.2346032	total: 968ms	remaining: 3.94s
197:	learn: 0.2334675	total: 973ms	remaining: 3.94s
198:	learn: 0.2321484	total: 978ms	remaining: 3.94s
199:	learn: 0.2314061	total: 983ms	remaining: 3.93s
200:	learn: 0.2303854	total: 988ms	remaining: 3.93s
201:	learn: 0.2295158	total: 993ms	remaining: 3.92s
202:	learn: 0.2286818	total: 997ms	remaining: 3.92s
203:	learn: 0.2279711	total: 1s	remaining: 3.91s
204:	learn: 0.2271386	total: 1.01s	remaining: 3.9s
205:	learn: 0.2261737	total: 1.01s	remaining: 3.9s
206:	learn: 0.2251147	total: 1.01s	remaining: 3.89s
207:	learn: 0.2242807	total: 1.02s	remaining: 3.88s
208:	learn: 0.2233548	total: 1.02s	remaining: 3.88s
209:	learn: 0.2223668	total: 1.03s	remaining: 3.87s
210:	learn: 0.2215450	total: 1.03s	remaining: 3.87s
211:	learn: 0.2209030	total: 1.04s	remaining: 3.86s
212:	learn: 0.2200819	total: 1.04s	remaining: 3.86s
213:	learn: 0.2191890	total: 1.05s	remaining: 3.85s
214:	learn: 0.2182397	total: 1.05s	remaining: 3.85s
215:	learn: 0.217

368:	learn: 0.1339100	total: 1.97s	remaining: 3.37s
369:	learn: 0.1336862	total: 1.98s	remaining: 3.36s
370:	learn: 0.1333699	total: 1.98s	remaining: 3.36s
371:	learn: 0.1330469	total: 1.99s	remaining: 3.35s
372:	learn: 0.1324920	total: 1.99s	remaining: 3.35s
373:	learn: 0.1318285	total: 2s	remaining: 3.34s
374:	learn: 0.1316070	total: 2s	remaining: 3.34s
375:	learn: 0.1313087	total: 2.01s	remaining: 3.33s
376:	learn: 0.1309577	total: 2.01s	remaining: 3.32s
377:	learn: 0.1306163	total: 2.02s	remaining: 3.32s
378:	learn: 0.1303691	total: 2.02s	remaining: 3.31s
379:	learn: 0.1301034	total: 2.02s	remaining: 3.31s
380:	learn: 0.1298502	total: 2.03s	remaining: 3.3s
381:	learn: 0.1292617	total: 2.04s	remaining: 3.29s
382:	learn: 0.1290192	total: 2.04s	remaining: 3.29s
383:	learn: 0.1285766	total: 2.04s	remaining: 3.28s
384:	learn: 0.1280675	total: 2.05s	remaining: 3.27s
385:	learn: 0.1276292	total: 2.05s	remaining: 3.27s
386:	learn: 0.1272556	total: 2.06s	remaining: 3.26s
387:	learn: 0.12705

538:	learn: 0.0875519	total: 4.35s	remaining: 3.72s
539:	learn: 0.0873054	total: 4.36s	remaining: 3.71s
540:	learn: 0.0869347	total: 4.37s	remaining: 3.7s
541:	learn: 0.0866802	total: 4.37s	remaining: 3.69s
542:	learn: 0.0865048	total: 4.38s	remaining: 3.69s
543:	learn: 0.0863418	total: 4.39s	remaining: 3.68s
544:	learn: 0.0861979	total: 4.39s	remaining: 3.67s
545:	learn: 0.0860139	total: 4.4s	remaining: 3.66s
546:	learn: 0.0858458	total: 4.41s	remaining: 3.65s
547:	learn: 0.0856329	total: 4.42s	remaining: 3.64s
548:	learn: 0.0854512	total: 4.42s	remaining: 3.63s
549:	learn: 0.0851951	total: 4.43s	remaining: 3.63s
550:	learn: 0.0850308	total: 4.44s	remaining: 3.62s
551:	learn: 0.0848662	total: 4.45s	remaining: 3.61s
552:	learn: 0.0845421	total: 4.45s	remaining: 3.6s
553:	learn: 0.0842821	total: 4.46s	remaining: 3.59s
554:	learn: 0.0840547	total: 4.47s	remaining: 3.58s
555:	learn: 0.0837371	total: 4.47s	remaining: 3.57s
556:	learn: 0.0835523	total: 4.48s	remaining: 3.56s
557:	learn: 0.0

702:	learn: 0.0623987	total: 5.52s	remaining: 2.33s
703:	learn: 0.0622941	total: 5.53s	remaining: 2.32s
704:	learn: 0.0622012	total: 5.54s	remaining: 2.32s
705:	learn: 0.0621044	total: 5.54s	remaining: 2.31s
706:	learn: 0.0620110	total: 5.55s	remaining: 2.3s
707:	learn: 0.0619155	total: 5.57s	remaining: 2.29s
708:	learn: 0.0617590	total: 5.57s	remaining: 2.29s
709:	learn: 0.0616425	total: 5.58s	remaining: 2.28s
710:	learn: 0.0614969	total: 5.58s	remaining: 2.27s
711:	learn: 0.0613518	total: 5.59s	remaining: 2.26s
712:	learn: 0.0612155	total: 5.61s	remaining: 2.26s
713:	learn: 0.0610797	total: 5.61s	remaining: 2.25s
714:	learn: 0.0609711	total: 5.62s	remaining: 2.24s
715:	learn: 0.0608913	total: 5.63s	remaining: 2.23s
716:	learn: 0.0607836	total: 5.63s	remaining: 2.22s
717:	learn: 0.0606091	total: 5.64s	remaining: 2.21s
718:	learn: 0.0604754	total: 5.65s	remaining: 2.21s
719:	learn: 0.0603370	total: 5.66s	remaining: 2.2s
720:	learn: 0.0602583	total: 5.66s	remaining: 2.19s
721:	learn: 0.

878:	learn: 0.0457880	total: 6.9s	remaining: 950ms
879:	learn: 0.0457050	total: 6.91s	remaining: 942ms
880:	learn: 0.0456212	total: 6.93s	remaining: 936ms
881:	learn: 0.0455792	total: 6.93s	remaining: 928ms
882:	learn: 0.0455032	total: 6.94s	remaining: 920ms
883:	learn: 0.0454442	total: 6.95s	remaining: 912ms
884:	learn: 0.0453875	total: 6.95s	remaining: 904ms
885:	learn: 0.0452719	total: 6.96s	remaining: 896ms
886:	learn: 0.0452308	total: 6.97s	remaining: 888ms
887:	learn: 0.0451741	total: 6.97s	remaining: 880ms
888:	learn: 0.0450867	total: 6.98s	remaining: 872ms
889:	learn: 0.0450332	total: 7s	remaining: 865ms
890:	learn: 0.0449131	total: 7.01s	remaining: 857ms
891:	learn: 0.0448354	total: 7.01s	remaining: 849ms
892:	learn: 0.0447465	total: 7.02s	remaining: 841ms
893:	learn: 0.0446623	total: 7.03s	remaining: 833ms
894:	learn: 0.0446070	total: 7.03s	remaining: 825ms
895:	learn: 0.0445125	total: 7.04s	remaining: 817ms
896:	learn: 0.0444529	total: 7.05s	remaining: 809ms
897:	learn: 0.04

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,precision_score,recall_score,f1_score

In [44]:
print('Accuracy for CatBoost Classifier',accuracy_score(y_test,y_pred))
print('Precision for CatBoost Classifier',precision_score(y_test,y_pred))
print('Recall for CatBoost Classifier',recall_score(y_test,y_pred))
print('F1 Score for CatBoost Classifier',f1_score(y_test,y_pred))

Accuracy for CatBoost Classifier 0.9743589743589743
Precision for CatBoost Classifier 0.96
Recall for CatBoost Classifier 1.0
F1 Score for CatBoost Classifier 0.9795918367346939


In [45]:
import pickle
import numpy as np
filename='model.pkl'
pickle.dump(cbc_f,open(filename,'wb'))

In [46]:
model=pickle.load(open('model.pkl','rb'))